rm    resultadosGenetico.txt
touch resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho10_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho20_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho30_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho40_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho50_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho60_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho70_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho80_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho90_variando1000_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando10_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando100_amostra10.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra1.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra2.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra3.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra4.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra5.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra6.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra7.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra8.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra9.txt >> resultadosGenetico.txt
./nj < ./instancias/tamanho100_variando1000_amostra10.txt >> resultadosGenetico.txt
