rm    resultadosGenetico.txt
touch resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando10_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando100_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho80_variando1000_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando10_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando100_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho90_variando1000_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando10_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando100_amostra10.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra1.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra2.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra3.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra4.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra5.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra6.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra7.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra8.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra9.txt >> resultadosGenetico.txt
./algoritmo_genetico < ./instancias/tamanho100_variando1000_amostra10.txt >> resultadosGenetico.txt
